#!/bin/bash
# Writes the current git commit hash into the xcconfig so Xcode
# bakes it into the Info.plist at build time.
#
# Usage:
#   ./scripts/set-build-info.sh          # auto-detect from git
#   ./scripts/set-build-info.sh abc1234  # explicit hash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."
XCCONFIG="$REPO_ROOT/SpatialStash/BuildInfo.xcconfig"

if [ $# -ge 1 ]; then
    HASH="$1"
elif command -v git &>/dev/null && git -C "$REPO_ROOT" rev-parse --short HEAD &>/dev/null; then
    HASH="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
else
    HASH="unknown"
fi

# Write the generated xcconfig (always overwrite)
cat > "$XCCONFIG" <<EOF
// Auto-generated by scripts/set-build-info.sh — do not edit manually.
COMMIT_HASH = ${HASH}
EOF

echo "Set COMMIT_HASH = ${HASH} in $(basename "$XCCONFIG")"
